---
title: "avg_state_money"
author:"Julia Portocarrero & Dasom An"
output: html_document
---

This document will try to answer the possible question: how much avg $ is contributed by state? (What state contributes the most $ per population?)

```{r}
library(tidyverse)
library(dplyr)
```

```{r}
load("contributions.rda")
```


```{r}
state_contrib <- contributions %>%
  select(transaction_amt, state) %>%
  group_by(state) %>%
  summarize(avg_donation = mean(transaction_amt))

```

Load census data (made from https://www.census.gov/data/datasets/2017/demo/popest/state-total.html data): 

```{r}
census_data <- read.csv("census_Data.csv") %>%
  select(state, X2017)
```

Join together the data
```{r}
state_contrib_census <- left_join(state_contrib, census_data, by = "state", na.rm = TRUE)

#test_data <- state_contrib_census %>%
  head(10)  

full_data <- state_contrib_census %>%
  mutate(donation_per_person = as.numeric(avg_donation)/as.numeric(X2017)) %>%
  na.omit()
```

Most and Least donations:
```{r}
most_data <- full_data %>%
  arrange(desc(donation_per_person)) %>%
  head(5) 
  
least_data <- full_data %>%
  arrange(donation_per_person) %>%
  head(5)

total_data <- rbind(most_data, least_data) #it's hard to see the numbers when you look at both together- bettero to have seperate graphs

```

Plot of both:
```{r}
ggplot(total_data) +
  geom_col(aes(x = reorder(state, -donation_per_person), y = donation_per_person, fill = donation_per_person), show.legend=F) +
  ylab("Avg donation per person") +
  xlab("state")
```

Plot Most Contributions:
```{r}
ggplot(most_data) +
  geom_col(aes(x = reorder(state, -donation_per_person), y = donation_per_person, fill = donation_per_person), show.legend=F) +
  ylab("Avg donation per person") +
  xlab("state")
  
#if the color difference is distracting, move fill out of aes() and choose a color
```

Plot Least Contributions:

```{r}
ggplot(least_data) +
  geom_col(aes(x = reorder(state, -donation_per_person), y = donation_per_person, fill = donation_per_person), show.legend=F) +
  ylab("Avg donation per person") +
  xlab("state")
```

